version: '2'
services:
  platform-docs:
    command: sh -c "npm ci && npm run dev:compose"
    ports:
      - "3000:3000"
    image: quay.io/mmarosi/platform-docs
    volumes:
      - ./docs:/pages/<repo-name>