docs_dir: ./pages
site_name: Better Platform Docs

markdown_extensions:
  - toc:
      permalink: "#"

nav:
- Frontend migrations:
  - Frontend components @3 -> @4 migration: 'guides/frontend-migrations/frontend-components-3-to-4.md'
  - Frontend components -> patternfly/react-component-groups migration: 'guides/frontend-components-to-PF-component-groups.md'
