import type { NextPage } from "next";
import Head from "next/head";
import { Button } from "@patternfly/react-core";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Button>Foo bar</Button>
      </main>
    </div>
  );
};

export default Home;
