import type { NextPage } from "next";
import Head from "next/head";
import { Button } from "@patternfly/react-core";
import Link from "next/link";
import SectionNavigation from "../components/Navigation/SectionNavigation";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <SectionNavigation />
      </main>
    </div>
  );
};

export default Home;
